#
# Copyright (C) 2018-2020 Intel Corporation
#
# SPDX-License-Identifier: MIT
#
version: "2.3"

services:
  cvat_db:
    container_name: cvat_db
    image: postgres:10-alpine
    networks:
      default:
        aliases:
          - db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: cvat
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - /home/weiru/fetc_data/.cvat/db:/var/lib/postgresql/data

  cvat_redis:
    container_name: cvat_redis
    image: redis:4.0-alpine
    networks:
      default:
        aliases:
          - redis
    restart: always

  cvat:
    container_name: cvat
    image: cvat/server
    restart: always
    depends_on:
      - cvat_redis
      - cvat_db
    build:
      context: .
      args:
        http_proxy:
        https_proxy:
        no_proxy: nuclio,${no_proxy}
        socks_proxy:
        USER: "django"
        DJANGO_CONFIGURATION: "production"
        TZ: "Etc/UTC"
        CLAM_AV: "no"
    environment:
      DJANGO_MODWSGI_EXTRA_ARGS: ""
      ALLOWED_HOSTS: '*'
      CVAT_REDIS_HOST: "cvat_redis"
      CVAT_POSTGRES_HOST: "cvat_db"
      MLSTEAM_CVAT_BASE_URL: ""
    volumes:
      - /home/weiru/fetc_data/.cvat/data:/home/django/data
      - /home/weiru/fetc_data/.cvat/keys:/home/django/keys
      - /home/weiru/fetc_data/.cvat/logs:/home/django/logs
      - /home/weiru/fetc_data/.cvat/models:/home/django/models
      - /home/weiru/fetc_data:/home/django/share:ro
      #- cvat_data:/home/django/data
      #- cvat_keys:/home/django/keys
      #- cvat_logs:/home/django/logs
      #- cvat_models:/home/django/models

  cvat_ui:
    container_name: cvat_ui
    image: cvat/ui
    restart: always
    build:
      context: .
      args:
        http_proxy:
        https_proxy:
        no_proxy:
        socks_proxy:
      dockerfile: Dockerfile.ui
    environment:
      REACT_APP_API_URL: ''
      MLSTEAM_CVAT_BASE_URL: ''
    networks:
      default:
        aliases:
          - ui
    depends_on:
      - cvat
    command: /bin/sh -c "/bin/sh /usr/share/nginx/html/patch_cvat_ui.sh && nginx -g 'daemon off;'"

  cvat_proxy:
    container_name: cvat_proxy
    image: nginx:stable-alpine
    restart: always
    depends_on:
      - cvat
      - cvat_ui
    environment:
      CVAT_HOST: 192.168.0.17
    ports:
      - "8088:80"
    volumes:
      - ./cvat_proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cvat_proxy/conf.d/cvat.conf.template:/etc/nginx/conf.d/cvat.conf.template:ro
    command: /bin/sh -c "envsubst '$$CVAT_HOST' < /etc/nginx/conf.d/cvat.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  serverless:
    container_name: nuclio
    image: quay.io/nuclio/dashboard:1.4.8-amd64
    restart: always
    networks:
      default:
        aliases:
          - nuclio
    volumes:
      - /tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      http_proxy:
      https_proxy:
      no_proxy: 172.28.0.1,${no_proxy}
      NUCLIO_CHECK_FUNCTION_CONTAINERS_HEALTHINESS: "true"
    ports:
      - "8070:8070"

networks:
  default:
    ipam:
      config:
        - subnet: 172.28.0.0/24
          gateway: 172.28.0.1

          #volumes:
          #  cvat_db:
          #  cvat_data:
          #  cvat_keys:
          #  cvat_logs:
          #  cvat_models:
